type CountryFlag = { code: string; iconSrc: string | null }

function normalizeCountry(value: string): string {
  return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").trim().toLowerCase().replace(/\s+/g, " ")
}

// ISO 3166-1 alpha-2, plus GB constituent-country codes and XK (user-assigned).
// Only explicit aliases: never guess a country from a partial name.
// Congo, Northern Ireland and Chinese Taipei intentionally retain text-only fallback.
// Artwork provenance/license and the read-only coverage audit: public/flags/README.md.
const countries: { code: string; names: string[] }[] = [
  { code: "GB-ENG", names: ["England","Inglaterra"] },
  { code: "DE", names: ["Germany","Alemanha"] },
  { code: "AR", names: ["Argentina"] },
  { code: "ES", names: ["Spain","Espanha"] },
  { code: "FR", names: ["France","França"] },
  { code: "IT", names: ["Italy","Itália"] },
  { code: "NL", names: ["Holland","Netherlands","Holanda","Países Baixos"] },
  { code: "KR", names: ["Korea Republic","South Korea"] },
  { code: "US", names: ["United States","United States of America","Estados Unidos"] },
  { code: "NO", names: ["Norway","Noruega"] },
  { code: "SE", names: ["Sweden"] },
  { code: "DK", names: ["Denmark"] },
  { code: "CN", names: ["China PR","China"] },
  { code: "BR", names: ["Brazil","Brasil"] },
  { code: "IE", names: ["Republic of Ireland","Ireland"] },
  { code: "PL", names: ["Poland"] },
  { code: "PT", names: ["Portugal"] },
  { code: "BE", names: ["Belgium"] },
  { code: "RO", names: ["Romania"] },
  { code: "SA", names: ["Saudi Arabia"] },
  { code: "AT", names: ["Austria"] },
  { code: "TR", names: ["Turkey"] },
  { code: "AU", names: ["Australia"] },
  { code: "GB-SCT", names: ["Scotland"] },
  { code: "CH", names: ["Switzerland"] },
  { code: "UY", names: ["Uruguay"] },
  { code: "IN", names: ["India"] },
  { code: "CO", names: ["Colombia"] },
  { code: "CL", names: ["Chile"] },
  { code: "HR", names: ["Croatia"] },
  { code: "PY", names: ["Paraguay"] },
  { code: "GB-WLS", names: ["Wales"] },
  { code: "NG", names: ["Nigeria"] },
  { code: "MA", names: ["Morocco"] },
  { code: "SN", names: ["Senegal"] },
  { code: "CI", names: ["Côte d'Ivoire","Ivory Coast"] },
  { code: "GH", names: ["Ghana"] },
  { code: "EC", names: ["Ecuador"] },
  { code: "RS", names: ["Serbia"] },
  { code: "JP", names: ["Japan"] },
  { code: "PE", names: ["Peru"] },
  { code: "GR", names: ["Greece"] },
  { code: "VE", names: ["Venezuela"] },
  { code: "CZ", names: ["Czech Republic","Czechia"] },
  { code: "UA", names: ["Ukraine"] },
  { code: "CA", names: ["Canada"] },
  { code: "BO", names: ["Bolivia"] },
  { code: "CM", names: ["Cameroon"] },
  { code: "ML", names: ["Mali"] },
  { code: "FI", names: ["Finland"] },
  { code: "XK", names: ["Kosovo"] },
  { code: "AL", names: ["Albania"] },
  { code: "HU", names: ["Hungary"] },
  { code: "DZ", names: ["Algeria"] },
  { code: "IS", names: ["Iceland"] },
  { code: "BA", names: ["Bosnia and Herzegovina"] },
  { code: "SK", names: ["Slovakia"] },
  { code: "SI", names: ["Slovenia"] },
  { code: "NZ", names: ["New Zealand"] },
  { code: "CD", names: ["Congo DR","Democratic Republic of the Congo"] },
  { code: "JM", names: ["Jamaica"] },
  { code: "GN", names: ["Guinea"] },
  { code: "GM", names: ["Gambia"] },
  { code: "GE", names: ["Georgia"] },
  { code: "TN", names: ["Tunisia"] },
  { code: "SR", names: ["Suriname"] },
  { code: "CV", names: ["Cape Verde Islands","Cabo Verde"] },
  { code: "MX", names: ["Mexico"] },
  { code: "BF", names: ["Burkina Faso"] },
  { code: "CY", names: ["Cyprus"] },
  { code: "AO", names: ["Angola"] },
  { code: "GW", names: ["Guinea-Bissau"] },
  { code: "ME", names: ["Montenegro"] },
  { code: "BG", names: ["Bulgaria"] },
  { code: "IL", names: ["Israel"] },
  { code: "MK", names: ["North Macedonia"] },
  { code: "SL", names: ["Sierra Leone"] },
  { code: "TG", names: ["Togo"] },
  { code: "RU", names: ["Russia"] },
  { code: "IQ", names: ["Iraq"] },
  { code: "LU", names: ["Luxembourg"] },
  { code: "AZ", names: ["Azerbaijan"] },
  { code: "ZA", names: ["South Africa"] },
  { code: "ZW", names: ["Zimbabwe"] },
  { code: "ID", names: ["Indonesia"] },
  { code: "CR", names: ["Costa Rica"] },
  { code: "CW", names: ["Curaçao"] },
  { code: "HT", names: ["Haiti"] },
  { code: "GA", names: ["Gabon"] },
  { code: "KM", names: ["Comoros"] },
  { code: "PA", names: ["Panama"] },
  { code: "KE", names: ["Kenya"] },
  { code: "SY", names: ["Syria"] },
  { code: "AE", names: ["United Arab Emirates"] },
  { code: "HN", names: ["Honduras"] },
  { code: "GQ", names: ["Equatorial Guinea"] },
  { code: "DO", names: ["Dominican Republic"] },
  { code: "EG", names: ["Egypt","Egito"] },
  { code: "BJ", names: ["Benin"] },
  { code: "AM", names: ["Armenia"] },
  { code: "ZM", names: ["Zambia"] },
  { code: "LV", names: ["Latvia"] },
  { code: "TT", names: ["Trinidad and Tobago"] },
  { code: "EE", names: ["Estonia"] },
  { code: "GD", names: ["Grenada"] },
  { code: "MT", names: ["Malta"] },
  { code: "HK", names: ["Hong Kong"] },
  { code: "LT", names: ["Lithuania"] },
  { code: "UG", names: ["Uganda"] },
  { code: "IR", names: ["Iran"] },
  { code: "MG", names: ["Madagascar"] },
  { code: "LR", names: ["Liberia"] },
  { code: "MR", names: ["Mauritania"] },
  { code: "GY", names: ["Guyana"] },
  { code: "MD", names: ["Moldova"] },
  { code: "CF", names: ["Central African Republic"] },
  { code: "SV", names: ["El Salvador"] },
  { code: "FO", names: ["Faroe Islands"] },
  { code: "PH", names: ["Philippines"] },
  { code: "UZ", names: ["Uzbekistan"] },
  { code: "KN", names: ["St. Kitts and Nevis"] },
  { code: "AG", names: ["Antigua and Barbuda"] },
  { code: "MZ", names: ["Mozambique"] },
  { code: "MS", names: ["Montserrat"] },
  { code: "TZ", names: ["Tanzania"] },
  { code: "LC", names: ["St. Lucia"] },
  { code: "LY", names: ["Libya"] },
  { code: "BI", names: ["Burundi"] },
  { code: "GT", names: ["Guatemala"] },
  { code: "PS", names: ["Palestine"] },
  { code: "CU", names: ["Cuba"] },
  { code: "BY", names: ["Belarus"] },
  { code: "MY", names: ["Malaysia"] },
  { code: "RW", names: ["Rwanda"] },
  { code: "LB", names: ["Lebanon"] },
  { code: "JO", names: ["Jordan"] },
  { code: "NA", names: ["Namibia"] },
  { code: "PK", names: ["Pakistan"] },
  { code: "BM", names: ["Bermuda"] },
  { code: "BB", names: ["Barbados"] },
  { code: "LK", names: ["Sri Lanka"] },
  { code: "GI", names: ["Gibraltar"] },
  { code: "TH", names: ["Thailand"] },
  { code: "NE", names: ["Niger"] },
  { code: "MW", names: ["Malawi"] },
  { code: "VU", names: ["Vanuatu"] },
  { code: "TJ", names: ["Tajikistan"] },
  { code: "BD", names: ["Bangladesh"] },
  { code: "AD", names: ["Andorra"] },
  { code: "SO", names: ["Somalia"] },
  { code: "TD", names: ["Chad"] },
  { code: "AF", names: ["Afghanistan"] },
  { code: "LI", names: ["Liechtenstein"] },
]
const flags = new Map<string, CountryFlag>()
for (const { code, names } of countries) {
  for (const name of [code, ...names]) {
    flags.set(normalizeCountry(name), { code, iconSrc: `/flags/${code.toLowerCase()}.svg` })
  }
}

export function getCountryFlag(country: string | null | undefined): CountryFlag | null {
  return country ? flags.get(normalizeCountry(country)) ?? null : null
}
